from ._image_collections import AbstractImageCollection, ImageCollection
from ._outputStrategies import OutputStrategy, SaveWarpedImagesOutputStrategy, SaveMatrixOutputStrategy
from ._ui import CoregisterUtilityApp